In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"F:\Codes\NLP\spam.csv")

df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
df['Spam'] = df['Category'].apply(lambda x : 1 if x == 'spam' else 0)

In [6]:
df.head()

  Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
# Before Training

df.shape

(5572, 3)

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df.Message,
    df.Spam,
    test_size=0.2
)

# X_train = Training messages
# X_test = Testing messages
# y_train = Training labels
# y_test = Testing labels
# test_size=0.2 = 20% data size to go into test and 80% will remain in data set

In [9]:
X_train.shape

(4457,)

In [10]:
X_test.shape

(1115,)

In [11]:
type(X_train)

pandas.core.series.Series

In [12]:
X_train[:4]

4514    Money i have won wining number 946 wot do i do...
243     Okay. No no, just shining on. That was meant t...
1395                 R we still meeting 4 dinner tonight?
90      Yeah do! Don‘t stand to close tho- you‘ll catc...
Name: Message, dtype: object

In [14]:
X_train[:4][4514]

'Money i have won wining number 946 wot do i do next'

In [15]:
type(y_train)

pandas.core.series.Series

In [16]:
y_train[:4]

4514    1
243     0
1395    0
90      0
Name: Spam, dtype: int64

In [17]:
type(X_train.values)

numpy.ndarray

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

# Vectorizer
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)

X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59415 stored elements and shape (4457, 7774)>

In [19]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(2, 7774))

In [20]:
X_train_cv.shape

(4457, 7774)

In [21]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'zyada', 'ú1', '〨ud'],
      shape=(7774,), dtype=object)

In [22]:
v.get_feature_names_out()[1000:1100]

array(['anytime', 'anyway', 'anyways', 'anywhere', 'apart', 'apartment',
       'apes', 'apeshit', 'aphex', 'apnt', 'apo', 'apologetic',
       'apologise', 'apologize', 'apology', 'app', 'apparently', 'appear',
       'appendix', 'applausestore', 'applebees', 'apples', 'application',
       'apply', 'appointment', 'appointments', 'appreciate',
       'appreciated', 'approaches', 'approaching', 'appropriate',
       'approve', 'approved', 'approx', 'apps', 'appt', 'appy', 'april',
       'aproach', 'aptitude', 'ar', 'arab', 'arabian', 'arcade',
       'archive', 'ard', 'are', 'area', 'aren', 'arent', 'arestaurant',
       'aretaking', 'areyouunique', 'argentina', 'argh', 'argue',
       'arguing', 'argument', 'arguments', 'aries', 'arise', 'arises',
       'arithmetic', 'arm', 'armand', 'armenia', 'arms', 'arng', 'arngd',
       'arnt', 'around', 'aroundn', 'arr', 'arrange', 'arrested',
       'arrival', 'arrive', 'arrived', 'arsenal', 'art', 'artists',
       'arts', 'arty', 'arul', 'arun', 'as', 'asap', 'asda', 'ashes',
       'ashley', 'ashwini', 'asia', 'asjesus', 'ask', 'askd', 'asked',
       'askin', 'asking', 'asks', 'aslamalaikkum'], dtype=object)

In [23]:
# Supported Method
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_params_html',
 '_html_repr',
 '_limit_features',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',
 'fit_transform',
 'fixed_vocabulary_',
 'get_feature_names_out',
 'get_metadata_routing',
 'get_params',
 'get_stop_words',
 'input',
 'inverse_transform',
 'lowercase',
 'max_df',
 'max_features',
 'min_df',
 'ngram_range',
 'preprocessor',
 'set_params',
 'stop_words',
 'strip_accents',
 'token_pattern',
 'tokenizer',
 'transform',
 'vocabulary',
 'vocabulary_']

In [24]:
v.vocabulary_

{'money': 4594,
 'have': 3369,
 'won': 7602,
 'wining': 7556,
 'number': 4881,
 '946': 717,
 'wot': 7637,
 'do': 2381,
 'next': 4788,
 'okay': 4938,
 'no': 4820,
 'just': 3889,
 'shining': 6108,
 'on': 4956,
 'that': 6844,
 'was': 7413,
 'meant': 4432,
 'to': 6965,
 'be': 1272,
 'signing': 6178,
 'but': 1569,
 'sounds': 6363,
 'better': 1329,
 'we': 7440,
 'still': 6504,
 'meeting': 4445,
 'dinner': 2335,
 'tonight': 6998,
 'yeah': 7705,
 'don': 2414,
 'stand': 6458,
 'close': 1849,
 'tho': 6895,
 'you': 7731,
 'll': 4173,
 'catch': 1680,
 'something': 6328,
 'appt': 1035,
 'is': 3759,
 'at': 1114,
 'lt': 4265,
 'time': 6933,
 'gt': 3273,
 'am': 925,
 'not': 4855,
 'my': 4688,
 'fault': 2802,
 'listen': 4155,
 'told': 6979,
 'twice': 7119,
 'how': 3533,
 'are': 1046,
 'doing': 2404,
 'the': 6848,
 'queen': 5548,
 'going': 3184,
 'for': 2951,
 'royal': 5867,
 'wedding': 7456,
 'hai': 3311,
 'dear': 2201,
 'friends': 3021,
 'this': 6888,
 'new': 4780,
 'amp': 943,
 'present': 5412,
 'by': 1583,
 'rajitha': 5583,
 'raj': 5580,
 'ranju': 5598,
 'like': 4128,
 'plan': 5255,
 'cardiff': 1647,
 'here': 3422,
 'and': 955,
 'cold': 1890,
 'sitting': 6211,
 'radiator': 5569,
 'thank': 6836,
 'god': 3177,
 'they': 6873,
 'in': 3653,
 'bed': 1286,
 'free': 2999,
 '1st': 332,
 'week': 7462,
 'entry': 2629,
 'textpod': 6829,
 'chance': 1722,
 'win': 7546,
 '40gb': 475,
 'ipod': 3749,
 'or': 4995,
 '250': 362,
 'cash': 1671,
 'every': 2679,
 'wk': 7583,
 'txt': 7126,
 'pod': 5305,
 '84128': 661,
 'ts': 7095,
 'cs': 2100,
 'www': 7670,
 'net': 4767,
 'custcare': 2132,
 '08712405020': 109,
 'purity': 5524,
 'of': 4915,
 'friendship': 3023,
 'between': 1332,
 'two': 7125,
 'about': 748,
 'smiling': 6276,
 'after': 844,
 'reading': 5626,
 'forwarded': 2977,
 'message': 4475,
 'its': 3777,
 'seeing': 6015,
 'name': 4709,
 'gud': 3279,
 'evng': 2693,
 'love': 4241,
 'hope': 3503,
 'your': 7737,
 'anything': 998,
 'drastic': 2452,
 'dare': 2167,
 'sell': 6032,
 'pc': 5154,
 'phone': 5213,
 'can': 1624,
 'pls': 5279,
 'send': 6039,
 'me': 4424,
 'mail': 4334,
 'all': 902,
 'know': 3969,
 'relatives': 5709,
 'coming': 1917,
 'deliver': 2242,
 'costs': 2034,
 'risks': 5828,
 'benefits': 1322,
 'else': 2578,
 'thanks': 6837,
 'haf': 3308,
 'found': 2979,
 'him': 3445,
 'feel': 2817,
 'so': 6304,
 'stupid': 6571,
 'da': 2148,
 'cam': 1617,
 'working': 7623,
 'never': 4776,
 'nothing': 4860,
 'what': 7501,
 'happened': 3339,
 'interview': 3724,
 'dunno': 2498,
 'cos': 2029,
 'late': 4038,
 'when': 7508,
 'reach': 5617,
 'inside': 3702,
 'already': 915,
 'ate': 1115,
 'spageddies': 6374,
 'lor': 4220,
 'it': 3770,
 'gals': 3081,
 'who': 7522,
 'laughing': 4047,
 'ask': 1093,
 'if': 3610,
 'sat': 5941,
 'them': 6856,
 'make': 4342,
 'then': 6860,
 'ok': 4937,
 'marvel': 4385,
 'mobile': 4566,
 'play': 5263,
 'official': 4927,
 'ultimate': 7156,
 'spider': 6401,
 'man': 4352,
 'game': 3084,
 '50': 528,
 'ur': 7227,
 'right': 5813,
 'now': 4868,
 'text': 6819,
 '83338': 651,
 '8ball': 705,
 'wallpaper': 7390,
 'sorry': 6352,
 'call': 1599,
 'later': 4041,
 'dont': 2417,
 'much': 4657,
 'image': 3626,
 'class': 1831,
 'got': 3214,
 'rumour': 5887,
 'buy': 1572,
 'apartment': 1005,
 'chennai': 1767,
 'went': 7485,
 'project': 5466,
 'centre': 1707,
 'de': 2195,
 'shop': 6129,
 'whats': 7503,
 'hi': 3434,
 'mandy': 4360,
 'sullivan': 6620,
 'calling': 1612,
 'from': 3036,
 'hotmix': 3524,
 'fm': 2926,
 'chosen': 1807,
 'receive': 5654,
 '5000': 530,
 '00': 0,
 'our': 5028,
 'easter': 2524,
 'prize': 5441,
 'draw': 2453,
 'please': 5272,
 'telephone': 6782,
 '09041940223': 163,
 'claim': 1823,
 'before': 1297,
 '29': 375,
 '03': 12,
 '05': 15,
 'will': 7543,
 'transferred': 7052,
 'someone': 6323,
 'lazy': 4058,
 'type': 7140,
 'forgot': 2963,
 'lect': 4079,
 'saw': 5955,
 'pouch': 5361,
 'nice': 4792,
 'bank': 1221,
 'granite': 3238,
 'issues': 3768,
 'strong': 6548,
 'explosive': 2738,
 'pick': 5227,
 'members': 4459,
 'up': 7211,
 'over': 5048,
 '300': 421,
 'nasdaq': 4720,
 'symbol': 6702,
 'cdgt': 1695,
 'per': 5172,
 'happy': 3344,
 'year': 7706,
 'darlin': 2172,
 'im': 3625,
 'way': 7435,
 'london': 4202,
 'been': 1292,
 'smashed': 6268,
 'into': 3727,
 'another': 975,
 'driver': 2466,
 'big': 1344,
 'dent': 2254,
 'really': 5636,
 'missing': 4533,
 'xxx': 7686,
 'help': 3410,
 'she': 6096,
 'tmr': 6959,
 'mum': 4666,
 've': 7284,
 'sent': 6049,
 'many': 4367,
 'messages': 4477,
 'since': 6190,
 'want': 7399,
 'actually': 798,
 'getting': 3137,
 'enjoy': 2611,
 'rest': 5779,
 'day': 2189,
 'bangbabes': 1219,
 'order': 5002,
 'should': 6142,
 'service': 6060,
 'msg': 4640,
 'download': 2439,
 'content': 1992,
 'goto': 3218,
 'wap': 7404,
 'bangb': 1218,
 'tv': 7115,
 'internet': 3723,
 'menu': 4470,
 'haha': 3309,
 'than': 6833,
 'ever': 2678,
 'any': 989,
 'could': 2040,
 'swing': 6693,
 'reassuring': 5645,
 'crazy': 2073,
 'world': 7626,
 'well': 7479,
 'called': 1606,
 'punto': 5518,
 'woulda': 7642,
 'worse': 7633,
 'yup': 7758,
 'girl': 3150,
 'does': 2391,
 'stay': 6480,
 'doesn': 2393,
 'need': 4748,
 'recovery': 5672,
 'id': 3599,
 'rather': 5601,
 'pass': 5127,
 'out': 5031,
 'while': 7518,
 'having': 3374,
 'fun': 3057,
 'cooped': 2014,
 'today': 6970,
 'parents': 5110,
 'tonite': 7000,
 'warner': 7409,
 'village': 7319,
 '83118': 648,
 'colin': 1891,
 'farrell': 2790,
 'swat': 6677,
 'wkend': 7584,
 'get': 3131,
 'med': 4438,
 'popcorn': 5332,
 'show': 6147,
 'ticket': 6924,
 'kiosk': 3954,
 'valid': 7268,
 '12': 280,
 'reply': 5749,
 'sony': 6340,
 'mre': 4636,
 'film': 2856,
 'offers': 4924,
 'everything': 2688,
 'stop': 6515,
 'let': 4102,
 'her': 3421,
 'dehydrated': 2234,
 'where': 7512,
 'those': 6896,
 'jus': 3888,
 'reached': 5619,
 'home': 3486,
 'go': 3172,
 'bathe': 1249,
 'first': 2884,
 'sis': 6203,
 'using': 7252,
 'tell': 6784,
 'finishes': 2874,
 'reserve': 5763,
 'saturday': 5948,
 'eve': 2671,
 'thirunelvali': 6887,
 'again': 851,
 'tirunelvali': 6942,
 'sunday': 6631,
 'see': 6013,
 'available': 1155,
 'book': 1425,
 'through': 6908,
 'tackle': 6712,
 'prob': 5446,
 'take': 6721,
 'give': 3156,
 'ride': 5812,
 'aiyah': 879,
 'watch': 7421,
 'until': 7209,
 'check': 1753,
 'taking': 6726,
 'part': 5117,
 'survey': 6664,
 'yesterday': 7717,
 '500': 529,
 'texts': 6830,
 'use': 7244,
 'however': 3537,
 'wish': 7566,
 'txts': 7134,
 '80160': 629,
 'txt43': 7128,
 'com': 1905,
 '50p': 535,
 'pocked': 5301,
 'there': 6865,
 'wan2': 7396,
 'meet': 4443,
 'greet': 3251,
 'with': 7574,
 'westlife': 7494,
 'm8': 4299,
 'currently': 2128,
 'tour': 7031,
 'unbreakable': 7164,
 'untamed': 7208,
 'unkempt': 7194,
 '83049': 647,
 'cost': 2031,
 'std': 6485,
 'good': 3196,
 'player': 5265,
 'why': 7529,
 'he': 3379,
 'unsold': 7203,
 'wats': 7430,
 'opinion': 4985,
 'abt': 754,
 'character': 1731,
 'boy': 1468,
 'best': 1325,
 'yo': 7726,
 'ass': 1103,
 'quick': 5554,
 'lookatme': 4210,
 'purchase': 5521,
 'video': 7310,
 'clip': 1846,
 'charged': 1733,
 '35p': 443,
 'think': 6879,
 'mmsto': 4558,
 '32323': 438,
 'attend': 1128,
 'rounds': 5862,
 'did': 2305,
 'made': 4319,
 'great': 3247,
 'too': 7003,
 'elaine': 2568,
 'confirmed': 1968,
 'kind': 3949,
 'missed': 4531,
 'train': 7041,
 'asthma': 1109,
 'attack': 1125,
 'nxt': 4892,
 'one': 4961,
 'half': 3317,
 'hr': 3544,
 'driving': 2468,
 'sure': 6655,
 'park': 5113,
 'bill': 1348,
 '33': 440,
 '65': 575,
 'thats': 6847,
 'bad': 1198,
 'probably': 5447,
 'tomorrow': 6989,
 'even': 2673,
 'hoping': 3511,
 'l8r': 3993,
 'malaria': 4347,
 'miss': 4529,
 'guys': 3296,
 'bani': 1220,
 'especially': 2657,
 'printer': 5435,
 'cool': 2013,
 'mean': 4427,
 'groovy': 3260,
 'wine': 7553,
 'groovying': 3261,
 'were': 7487,
 'gonna': 3195,
 'some': 6319,
 'tacos': 6713,
 'put': 5532,
 'silent': 6180,
 'mode': 4577,
 'collecting': 1897,
 'laptop': 4028,
 'configure': 1965,
 'settings': 6066,
 'izzit': 3786,
 'argh': 1054,
 'fuck': 3046,
 'nobody': 4823,
 'town': 7033,
 'ummmmmaah': 7160,
 'returns': 5794,
 'sweet': 6684,
 'heart': 3393,
 'birthday': 1363,
 'oredi': 5005,
 'ma': 4302,
 'fan': 2780,
 'noe': 4824,
 'specify': 6388,
 'domain': 2413,
 'as': 1085,
 'nusstu': 4886,
 'sch': 5968,
 'stuff': 6565,
 'po': 5287,
 'box': 1453,
 'customer': 2134,
 'representative': 5754,
 'freephone': 3007,
 '0808': 57,
 '145': 298,
 '4742': 499,
 '9am': 726,
 '11pm': 279,
 'guaranteed': 3277,
 '1000': 258,
 'shall': 6085,
 'idc': 3600,
 'weaseling': 7447,
 'shit': 6115,
 'row': 5864,
 'mummy': 4668,
 'being': 1308,
 'positive': 5345,
 'negative': 4757,
 'wait': 7375,
 'hmmmm': 3466,
 'ill': 3622,
 'babe': 1188,
 'most': 4617,
 'likely': 4130,
 'wanna': 7398,
 'loans': 4181,
 'purpose': 5526,
 'credit': 2078,
 'tenants': 6796,
 'welcome': 7477,
 'noworriesloans': 4872,
 '08717111821': 129,
 'baby': 1191,
 'ive': 3782,
 'back': 1195,
 'work': 7619,
 'wanting': 7402,
 'allday': 905,
 'didnt': 2308,
 'piss': 5245,
 'off': 4917,
 'house': 3529,
 'maid': 4333,
 'murderer': 4675,
 'coz': 2059,
 'murdered': 4674,
 'th': 6832,
 'january': 3804,
 'public': 5507,
 'holiday': 3482,
 'govt': 3223,
 'instituitions': 3711,
 'closed': 1851,
 'including': 3662,
 'post': 5351,
 'office': 4925,
 'understand': 7175,
 'di': 2296,
 'yijue': 7723,
 're': 5616,
 'pm': 5285,
 'esaplanade': 2651,
 'food': 2942,
 'staying': 6483,
 'weekend': 7464,
 'start': 6468,
 'hear': 3389,
 'ic': 3592,
 'lotta': 4233,
 'childporn': 1785,
 'cars': 1667,
 'weekly': 7466,
 'mob': 4564,
 'tones': 6992,
 'ready': 5627,
 'weeks': 7467,
 'include': 3660,
 'frog': 3035,
 'axel': 1176,
 'akon': 885,
 'lonely': 4204,
 'black': 1373,
 'eyed': 2751,
 'more': 4609,
 'info': 3686,
 'write': 7649,
 'dictionary': 2304,
 'cover': 2056,
 'screen': 5989,
 'hand': 3324,
 'press': 5416,
 'gently': 3125,
 'remove': 5731,
 'interesting': 3719,
 'only': 4967,
 'stalk': 6455,
 'profiles': 5461,
 'wuld': 7668,
 'without': 7577,
 'thought': 6899,
 'alone': 912,
 'mite': 4543,
 'break': 1488,
 'everyboy': 2682,
 'needs': 4753,
 'his': 3452,
 'lady': 4006,
 'xxxxxxxx': 7692,
 'college': 1900,
 'sunshine': 6638,
 'quiz': 5561,
 'wkly': 7587,
 'top': 7011,
 'dvd': 2505,
 'which': 7517,
 'country': 2046,
 'liverpool': 4168,
 'played': 5264,
 'mid': 4487,
 'ansr': 977,
 '82277': 643,
 'sp': 6371,
 'tyrone': 7142,
 'lab': 4000,
 'goggles': 3180,
 'thk': 6889,
 'wan': 7395,
 'come': 1911,
 'wat': 7420,
 'selected': 6026,
 'british': 1509,
 'hotels': 3522,
 'valued': 7272,
 '350': 441,
 'dial': 2297,
 '08712300220': 98,
 'national': 4726,
 'rate': 5599,
 'bx526': 1582,
 'sw73ss': 6671,
 'nottingham': 4864,
 'hrs': 3546,
 '63miles': 574,
 'thing': 6877,
 '40mph': 476,
 'hey': 3430,
 'ho': 3471,
 'restrict': 5782,
 'eating': 2529,
 'anythin': 997,
 'likes': 4131,
 'days': 2190,
 'arr': 1072,
 'oscar': 5017,
 'justbeen': 3890,
 'overa': 5049,
 'broke': 1514,
 'brains': 1479,
 'mush': 4677,
 'gettin': 3136,
 'rdy': 5615,
 'ship': 6110,
 'comp': 1926,
 'same': 5923,
 'hopefully': 3506,
 'lose': 4222,
 'few': 2832,
 'kg': 3933,
 'mon': 4591,
 'hip': 3449,
 'hop': 3502,
 'orchard': 5001,
 'weigh': 7468,
 'lit': 4161,
 'hair': 3313,
 'fire': 2878,
 'would': 7641,
 'guild': 3290,
 'bristol': 1508,
 'road': 5832,
 'somewhere': 6333,
 'touch': 7027,
 'plans': 5260,
 'flight': 2906,
 'trouble': 7080,
 'convincing': 2008,
 'tel': 6780,
 'once': 4960,
 'neglect': 4758,
 'msgs': 4646,
 'read': 5623,
 'worry': 7631,
 'hen': 3418,
 'night': 4800,
 'aight': 871,
 'mu': 4655,
 'somebody': 6321,
 'door': 2423,
 'hello': 3407,
 'little': 4164,
 'party': 5125,
 'animal': 962,
 'buzz': 1578,
 'grins': 3255,
 'reminding': 5727,
 'loved': 4242,
 'naughty': 4732,
 'adoring': 816,
 'kiss': 3957,
 'cine': 1817,
 'down': 2438,
 'plaza': 5270,
 'mah': 4330,
 'yes': 7715,
 'lookin': 4212,
 'ya': 7696,
 'say': 5956,
 'onam': 4957,
 'sirji': 6202,
 'fine': 2868,
 'remembered': 5720,
 'met': 4481,
 'an': 950,
 'insurance': 3713,
 'person': 5189,
 'qatar': 5539,
 'insha': 3700,
 'allah': 903,
 'rakhesh': 5585,
 'ex': 2702,
 'tata': 6746,
 'aig': 870,
 'joined': 3853,
 'tissco': 6945,
 'tayseer': 6756,
 'came': 1619,
 'ago': 861,
 'hill': 3442,
 'monster': 4601,
 'things': 6878,
 'busy': 1568,
 'though': 6898,
 'glad': 3160,
 'wasted': 7418,
 'applebees': 1020,
 'makes': 4343,
 'sense': 6045,
 'btw': 1536,
 'carlos': 1661,
 'difficult': 2319,
 'smoke': 6278,
 'second': 6003,
 'batch': 1247,
 'gas': 3099,
 'said': 5911,
 'hours': 3528,
 'almost': 911,
 'gautham': 3102,
 'alrite': 917,
 'gail': 3075,
 'neva': 4775,
 'wrong': 7656,
 'care': 1650,
 'l8tr': 3995,
 'hun': 3560,
 'yaxxx': 7702,
 'finished': 2873,
 'yet': 7718,
 'smile': 6272,
 'pleasure': 5275,
 'pain': 5078,
 'pours': 5366,
 'rain': 5577,
 'sum1': 6622,
 'hurts': 3574,
 'becoz': 1285,
 'loves': 4249,
 'bot': 1443,
 'notes': 4858,
 'juz': 3893,
 'rem': 5716,
 '09090900040': 243,
 'extreme': 2748,
 'dirty': 2345,
 'live': 4165,
 'chat': 1743,
 'total': 7024,
 'privacy': 5438,
 'knows': 3972,
 'sic': 6168,
 'listening': 4158,
 '60p': 567,
 'min': 4501,
 '24': 358,
 '7mp': 616,
 '0870753331018': 87,
 'scotland': 5979,
 'showing': 6152,
 'jjc': 3842,
 'tendencies': 6797,
 'dream': 2454,
 'accept': 764,
 'begging': 1300,
 'change': 1724,
 'gifts': 3145,
 'trying': 7094,
 'throw': 6909,
 'myself': 4694,
 'cliff': 1845,
 'congrats': 1972,
 '3g': 453,
 'videophones': 7312,
 'yours': 7741,
 '09063458130': 207,
 'videochat': 7311,
 'wid': 7533,
 'mates': 4399,
 'java': 3810,
 'games': 3085,
 'dload': 2378,
 'polyph': 5321,
 'music': 4679,
 'noline': 4833,
 'rentl': 5739,
 'done': 2415,
 'costa': 2032,
 'del': 2236,
 'sol': 6313,
 'await': 1165,
 'collection': 1898,
 '09050090044': 171,
 'toclaim': 6969,
 'sae': 5905,
 'tcs': 6760,
 'pobox334': 5295,
 'stockport': 6508,
 'sk38xh': 6219,
 'max10mins': 4413,
 'wont': 7609,
 'permission': 5185,
 'try': 7092,
 'end': 2596,
 'course': 2052,
 'coimbatore': 1884,
 'fyi': 3070,
 'has': 3355,
 'early': 2514,
 'morning': 4613,
 'crashing': 2070,
 'place': 5251,
 'urgent': 7231,
 'important': 3641,
 'information': 3688,
 '02': 7,
 'user': 7248,
 'lucky': 4272,
 'find': 2865,
 'log': 4190,
 'onto': 4970,
 'http': 3548,
 'urawinner': 7228,
 'fantastic': 2786,
 'surprise': 6661,
 'awaiting': 1166,
 'yar': 7700,
 'horse': 3516,
 'racing': 5568,
 'eat': 2526,
 'earlier': 2512,
 'chicken': 1778,
 'rice': 5809,
 'planning': 5259,
 'usually': 7256,
 'stops': 6522,
 'hella': 3406,
 'weed': 7461,
 'ryan': 5898,
 'shd': 6095,
 'bar': 1227,
 'sound': 6361,
 'logo': 4193,
 'lover': 4246,
 'names': 4713,
 'name1': 4710,
 'name2': 4711,
 'mobno': 4571,
 'eg': 2553,
 'adam': 800,
 '07123456789': 25,
 '87077': 678,
 'yahoo': 7698,
 'pobox36504w45wq': 5296,
 'txtno': 7133,
 'ads': 820,
 '150p': 306,
 'agree': 862,
 'thinkin': 6881,
 'ipad': 3746,
 'macho': 4311,
 'question': 5551,
 'wah': 7369,
 'save': 5952,
 'hee': 3400,
 'jay': 3811,
 'wants': 7403,
 'wylie': 7671,
 'tampa': 6738,
 'sarasota': 5934,
 'pay': 5144,
 'yrs': 7749,
 'sundayish': 6632,
 'tired': 6939,
 'special': 6383,
 'had': 3307,
 'plenty': 5277,
 'hate': 3361,
 'single': 6196,
 'mine': 4507,
 'messaged': 4476,
 'talk': 6729,
 'word': 7617,
 'congratulations': 1974,
 'awarded': 1169,
 'either': 2563,
 'supply': 6647,
 'cds': 1696,
 'virgin': 7324,
 'records': 5670,
 'mystery': 4696,
 'gift': 3143,
 '09061104283': 186,
 'smsco': 6285,
 '50pm': 537,
 'approx': 1033,
 '3mins': 458,
 'men': 4464,
 'always': 923,
 'beautiful': 1278,
 'intelligent': 3714,
 'caring': 1659,
 'loving': 4251,
 'adjustable': 810,
 'cooperative': 2015,
 'wife': 7536,
 'law': 4052,
 'allows': 910,
 'general': 3118,
 'price': 5426,
 'oz': 5067,
 'calls': 1614,
 'bought': 1449,
 'ringtone': 5822,
 'costing': 2033,
 'pound': 5362,
 'offering': 4923,
 'etc': 2663,
 'yourself': 7742,
 'lots': 4230,
 'used': 7245,
 'ones': 4962,
 'model': 4578,
 'youi': 7733,
 'bring': 1503,
 'match': 4395,
 'challenge': 1718,
 'instead': 3710,
 'respond': 5773,
 'immed': 3635,
 'cooking': 2012,
 'ding': 2333,
 'fassyole': 2792,
 'blacko': 1375,
 'londn': 4201,
 'eatin': 2528,
 'wif': 7535,
 'frens': 3012,
 'lei': 4089,
 ...}

In [27]:
# To View Where the non zero values are
X_train_np = X_train_cv.toarray()
np.where(X_train_np[0] != 0)

(array([ 717, 2381, 3369, 4594, 4788, 4881, 7556, 7602, 7637]),)

In [29]:
# Training the model

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train_cv, y_train)

MultinomialNB()

In [30]:
X_test_cv = v.transform(X_test)

In [34]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

# 0 = Not spam & 1 = Spam
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       963
           1       0.97      0.93      0.95       152

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

In [33]:
emails = [
    'Hey mohan, can we get together to watch football game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)

model.predict(emails_count)

array([0, 1])

In [36]:
# Different way
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [37]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [38]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       963
           1       0.97      0.93      0.95       152

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115