In [ ]:
""" Text Classification Using Spacy Word Embeddings
Problem Statement
    Fake news refers to misinformation or disinformation in the country which is spread through word of mouth and more recently through digital communication such as What's app messages, social media posts, etc.
    Fake news spreads faster than real news and creates problems and fear among groups and in society.
    We are going to address these problems using classical NLP techniques and going to classify whether a given message/ text is Real or Fake Message.
    We will use glove embeddings from spacy which is trained on massive wikipedia dataset to pre-process and text vectorization and apply different classification algorithms.
"""

In [5]:
import pandas as pd

#read the dataset with name "Fake_Real_Data.csv" and store it in a variable df
df = pd.read_csv(r"F:\Codes\NLP\News.csv")

#print the shape of dataframe
print(df.shape)

#print top 5 rows
df.head(5)

(44919, 2)

                                                text label
0  WASHINGTON (Reuters) - The head of a conservat...  Real
1  WASHINGTON (Reuters) - Transgender people will...  Real
2  WASHINGTON (Reuters) - The special counsel inv...  Real
3  WASHINGTON (Reuters) - Trump campaign adviser ...  Real
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  Real

In [6]:
#check the distribution of labels 
df['label'].value_counts()

label
Fake    23502
Real    21417
Name: count, dtype: int64

In [9]:
#Add the new column which gives a unique number to each of these labels 
df['label_num'] = df['label'].map({'Fake' : 0, 'Real': 1})

#check the results with top 5 rows
df.head(5)

                                                text label  label_num
0  WASHINGTON (Reuters) - The head of a conservat...  Real          1
1  WASHINGTON (Reuters) - Transgender people will...  Real          1
2  WASHINGTON (Reuters) - The special counsel inv...  Real          1
3  WASHINGTON (Reuters) - Trump campaign adviser ...  Real          1
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  Real          1

In [10]:
# spacy word vectors and store them in a pandas dataframe

In [11]:
import spacy
nlp = spacy.load("en_core_web_lg")

In [ ]:
df['vector'] = df['text'].apply(lambda text: nlp(text).vector)  

df.head()

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df.vector.values,
    df.label_num,
    test_size=0.2,
    random_state=2022
)

In [ ]:
import numpy as np

X_train_2d = np.stack(X_train)
X_test_2d = np.stack(X_test)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled_train_embed = scaler.fit_transform(X_train_2d)
scaled_test_embed = scaler.transform(X_test_2d)

clf = MultinomialNB()
clf.fit(scaled_train_embed, y_train)

In [ ]:
y_pred = clf.predict(scaled_test_embed)

print(classification_report(y_test, y_pred))

In [ ]:
from  sklearn.neighbors import KNeighborsClassifier

#1. creating a KNN model object
clf = KNeighborsClassifier(n_neighbors = 5, metric = 'euclidean')

#2. fit with all_train_embeddings and y_train
clf.fit(X_train_2d, y_train)

#3. get the predictions for all_test_embeddings and store it in y_pred
y_pred = clf.predict(X_test_2d)

#4. print the classfication report
print(classification_report(y_test, y_pred))

In [ ]:
# confusion matrix for the best model
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

from matplotlib import pyplot as plt
import seaborn as sn
plt.figure(figsize = (10,7))
sn.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Prediction')
plt.ylabel('Truth')